"""update user and kb tables

Revision ID: 0d1af8f55198
Revises: 3f4ac1fe5355
Create Date: 2026-08-31 16:08:33.387310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d1af8f55198'
down_revision: Union[str, Sequence[str], None] = '3f4ac1fe5355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge_base', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('knowledge_base', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_knowledge_base_created_at'), 'knowledge_base', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_base_updated_at'), 'knowledge_base', ['updated_at'], unique=False)
    op.create_foreign_key(None, 'knowledge_base', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('company_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('description', sa.String(length=255), nullable=True))
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_company_name'), 'users', ['company_name'], unique=False)
    op.create_index(op.f('ix_users_description'), 'users', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_description'), table_name='users')
    op.drop_index(op.f('ix_users_company_name'), table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_column('users', 'description')
    op.drop_column('users', 'company_name')
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_base_updated_at'), table_name='knowledge_base')
    op.drop_index(op.f('ix_knowledge_base_created_at'), table_name='knowledge_base')
    op.drop_column('knowledge_base', 'user_id')
    op.drop_column('knowledge_base', 'updated_at')
    op.drop_column('knowledge_base', 'created_at')
    # ### end Alembic commands ###
