"""map kb to document

Revision ID: f7fc4d00950c
Revises: 0d1af8f55198
Create Date: 2026-09-01 19:28:05.991965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7fc4d00950c'
down_revision: Union[str, Sequence[str], None] = '0d1af8f55198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_base', sa.Column('document_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'knowledge_base', 'documents', ['document_id'], ['id'])
    op.create_index(op.f('ix_knowledge_base_document_id'), 'knowledge_base', ['document_id'], unique=False)
    op.drop_column('knowledge_base', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_knowledge_base_document_id'), table_name='knowledge_base')
    op.drop_constraint(None, 'knowledge_base', type_='foreignkey')
    op.drop_column('knowledge_base', 'document_id')
    op.add_column('knowledge_base', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'knowledge_base', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_knowledge_base_user_id'), 'knowledge_base', ['user_id'], unique=False)
    # ### end Alembic commands ###
